# Generated by Django 4.0.5 on 2022-06-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0003_alter_cardpreference_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPreferance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbapp.accountpreferance'),
        ),
    ]
